spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/5i5i
    username: root
    password: yhlee0318**
  thymeleaf:
    cache: false


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # 첫 배포 이후 validate 으로 수정

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


